tags:
- name: Stable diffusion
  description: stable diffusion API

paths:
# [POST] img
  /img:
    post:
      tags:
      - Images
      summary: Generate imgae based on prompt
      parameters:
      - name: body
        in: body
        description: prompt
        required: true
        schema:
          $ref: '#/definitions/img'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'

# definitions
definitions:
  img:
    type: object
    required:
        - text
    properties:
      text:
        type: string
        description: Text to image prompt

schemes:
 - https
 - http
